// Mock data for Connect & Conquer

const userProfile = {
  name: "Alex Morgan",
  headline: "Senior Full-Stack Engineer",
  location: "San Francisco, CA",
  avatar: "",
  email: "alex.morgan@email.com",
  skills: [
    { name: "React", level: 95 },
    { name: "TypeScript", level: 90 },
    { name: "Node.js", level: 88 },
    { name: "Python", level: 82 },
    { name: "AWS", level: 78 },
    { name: "System Design", level: 85 },
    { name: "GraphQL", level: 80 },
    { name: "Docker", level: 75 },
  ],
  careerGoals: {
    targetRoles: ["Staff Engineer", "Engineering Manager", "Tech Lead"],
    salaryRange: { min: 180000, max: 280000 },
    preferredCompanies: ["Google", "Stripe", "Vercel", "Netflix", "Figma"],
    preferredLocations: ["San Francisco", "Remote", "New York"],
  },
};

const jobListings = [
  {
    id: "1",
    title: "Staff Software Engineer",
    company: "Stripe",
    logo: "S",
    location: "San Francisco, CA",
    salary: "$220K - $310K",
    matchScore: 96,
    type: "Full-time",
    level: "Senior",
    posted: "2 days ago",
    skills: ["React", "TypeScript", "Node.js", "AWS"],
    matchReasons: [
      "95% skill overlap with requirements",
      "Your system design experience is a strong match",
      "Located in your preferred city",
      "Salary within your target range",
    ],
    description:
      "Lead the development of Stripe's next-generation payment infrastructure. You'll work on high-throughput, low-latency systems processing billions of dollars.",
    skillGap: ["Rust", "Kafka"],
  },
  {
    id: "2",
    title: "Engineering Manager, Frontend",
    company: "Vercel",
    logo: "V",
    location: "Remote",
    salary: "$200K - $280K",
    matchScore: 93,
    type: "Full-time",
    level: "Manager",
    posted: "1 day ago",
    skills: ["React", "Next.js", "TypeScript", "Leadership"],
    matchReasons: [
      "Strong React/Next.js expertise",
      "Remote position matches your preference",
      "Career goal alignment: Engineering Manager",
      "Vercel is in your preferred companies",
    ],
    description:
      "Lead a team of frontend engineers building the future of web deployment. Drive technical strategy and mentor engineers.",
    skillGap: ["People Management Certification"],
  },
  {
    id: "3",
    title: "Senior Software Engineer",
    company: "Netflix",
    logo: "N",
    location: "Los Gatos, CA",
    salary: "$250K - $400K",
    matchScore: 91,
    type: "Full-time",
    level: "Senior",
    posted: "3 days ago",
    skills: ["React", "Node.js", "Python", "Microservices"],
    matchReasons: [
      "88% technical skill match",
      "Netflix is in your preferred companies",
      "Strong compensation package",
      "Microservices experience valued",
    ],
    description:
      "Build the next generation of Netflix's streaming platform. Work on systems serving 200M+ subscribers worldwide.",
    skillGap: ["Java", "Spring Boot"],
  },
  {
    id: "4",
    title: "Tech Lead, Platform",
    company: "Figma",
    logo: "F",
    location: "San Francisco, CA",
    salary: "$210K - $320K",
    matchScore: 89,
    type: "Full-time",
    level: "Lead",
    posted: "5 days ago",
    skills: ["TypeScript", "WebAssembly", "System Design", "C++"],
    matchReasons: [
      "Tech Lead aligns with career goals",
      "Figma is in your preferred companies",
      "Strong system design background",
      "SF location preference match",
    ],
    description:
      "Lead the platform team building Figma's collaborative editing engine. Push the boundaries of what's possible in the browser.",
    skillGap: ["WebAssembly", "C++"],
  },
  {
    id: "5",
    title: "Staff Engineer, Infrastructure",
    company: "Google",
    logo: "G",
    location: "Mountain View, CA",
    salary: "$240K - $380K",
    matchScore: 87,
    type: "Full-time",
    level: "Staff",
    posted: "1 week ago",
    skills: ["Python", "Go", "Kubernetes", "System Design"],
    matchReasons: [
      "Google is your top preferred company",
      "Staff level matches career goals",
      "System design expertise valued",
      "Strong compensation range",
    ],
    description:
      "Design and build Google Cloud's next-generation infrastructure. Work on systems that power millions of developers.",
    skillGap: ["Go", "Kubernetes"],
  },
  {
    id: "6",
    title: "Principal Engineer",
    company: "Datadog",
    logo: "D",
    location: "New York, NY",
    salary: "$230K - $350K",
    matchScore: 84,
    type: "Full-time",
    level: "Principal",
    posted: "4 days ago",
    skills: ["Python", "Go", "Distributed Systems", "Observability"],
    matchReasons: [
      "NY is in your preferred locations",
      "Principal level pathway from Staff",
      "Strong Python background",
      "Distributed systems experience",
    ],
    description:
      "Define the technical direction for Datadog's core observability platform. Architect systems handling trillions of data points daily.",
    skillGap: ["Go", "Observability"],
  },
];

const connections = [
  {
    id: "c1",
    name: "Sarah Chen",
    headline: "VP of Engineering at Stripe",
    company: "Stripe",
    avatar: "",
    mutualConnections: 12,
    relevanceScore: 98,
    status: "suggested",
    tags: ["Hiring Manager", "Stripe", "Engineering Leadership"],
  },
  {
    id: "c2",
    name: "Marcus Johnson",
    headline: "Staff Engineer at Google",
    company: "Google",
    avatar: "",
    mutualConnections: 8,
    relevanceScore: 94,
    status: "suggested",
    tags: ["Staff Engineer", "Google", "Infrastructure"],
  },
  {
    id: "c3",
    name: "Emily Rodriguez",
    headline: "Engineering Manager at Vercel",
    company: "Vercel",
    avatar: "",
    mutualConnections: 5,
    relevanceScore: 92,
    status: "connected",
    tags: ["Eng Manager", "Vercel", "Frontend"],
  },
  {
    id: "c4",
    name: "David Kim",
    headline: "Senior Engineer at Netflix",
    company: "Netflix",
    avatar: "",
    mutualConnections: 3,
    relevanceScore: 88,
    status: "pending",
    tags: ["Senior Engineer", "Netflix", "Streaming"],
  },
  {
    id: "c5",
    name: "Priya Patel",
    headline: "Tech Lead at Figma",
    company: "Figma",
    avatar: "",
    mutualConnections: 7,
    relevanceScore: 90,
    status: "connected",
    tags: ["Tech Lead", "Figma", "Platform"],
  },
  {
    id: "c6",
    name: "James Wilson",
    headline: "Recruiter at Google",
    company: "Google",
    avatar: "",
    mutualConnections: 15,
    relevanceScore: 96,
    status: "suggested",
    tags: ["Recruiter", "Google", "Talent Acquisition"],
  },
  {
    id: "c7",
    name: "Lisa Chang",
    headline: "Director of Engineering at Datadog",
    company: "Datadog",
    avatar: "",
    mutualConnections: 4,
    relevanceScore: 85,
    status: "connected",
    tags: ["Director", "Datadog", "Observability"],
  },
  {
    id: "c8",
    name: "Ryan Foster",
    headline: "Principal Engineer at Meta",
    company: "Meta",
    avatar: "",
    mutualConnections: 6,
    relevanceScore: 82,
    status: "suggested",
    tags: ["Principal", "Meta", "Infrastructure"],
  },
];

const applications = [
  {
    id: "a1",
    jobTitle: "Staff Software Engineer",
    company: "Stripe",
    logo: "S",
    status: "interview",
    appliedDate: "2026-02-01",
    lastUpdate: "2026-02-15",
    nextStep: "Technical Interview - Feb 20",
    notes: "Passed initial screen. System design round scheduled.",
    matchScore: 96,
  },
  {
    id: "a2",
    jobTitle: "Engineering Manager",
    company: "Vercel",
    logo: "V",
    status: "screening",
    appliedDate: "2026-02-05",
    lastUpdate: "2026-02-12",
    nextStep: "Recruiter call - Feb 18",
    notes: "Resume reviewed. Recruiter reached out for availability.",
    matchScore: 93,
  },
  {
    id: "a3",
    jobTitle: "Senior Software Engineer",
    company: "Netflix",
    logo: "N",
    status: "applied",
    appliedDate: "2026-02-10",
    lastUpdate: "2026-02-10",
    nextStep: "Awaiting response",
    notes: "Application submitted through referral.",
    matchScore: 91,
  },
  {
    id: "a4",
    jobTitle: "Tech Lead",
    company: "Figma",
    logo: "F",
    status: "offer",
    appliedDate: "2026-01-15",
    lastUpdate: "2026-02-14",
    nextStep: "Review offer details",
    notes: "Offer received! $280K base + equity. Decision due Feb 22.",
    matchScore: 89,
  },
  {
    id: "a5",
    jobTitle: "Staff Engineer",
    company: "Google",
    logo: "G",
    status: "interview",
    appliedDate: "2026-01-20",
    lastUpdate: "2026-02-13",
    nextStep: "Final round - Feb 21",
    notes: "Passed coding rounds. Team matching phase.",
    matchScore: 87,
  },
  {
    id: "a6",
    jobTitle: "Senior Platform Engineer",
    company: "Shopify",
    logo: "Sh",
    status: "rejected",
    appliedDate: "2026-01-10",
    lastUpdate: "2026-02-08",
    nextStep: "—",
    notes: "Position filled internally. Encouraged to apply again.",
    matchScore: 78,
  },
  {
    id: "a7",
    jobTitle: "Principal Engineer",
    company: "Datadog",
    logo: "D",
    status: "applied",
    appliedDate: "2026-02-14",
    lastUpdate: "2026-02-14",
    nextStep: "Awaiting response",
    notes: "Applied with Lisa Chang's referral.",
    matchScore: 84,
  },
  {
    id: "a8",
    jobTitle: "Senior Frontend Engineer",
    company: "Linear",
    logo: "L",
    status: "screening",
    appliedDate: "2026-02-08",
    lastUpdate: "2026-02-16",
    nextStep: "Take-home assignment due Feb 19",
    notes: "Received take-home challenge. 3-day deadline.",
    matchScore: 82,
  },
];

const referrals = [
  {
    id: "r1",
    targetCompany: "Stripe",
    targetRole: "Staff Software Engineer",
    referrer: "Sarah Chen",
    referrerTitle: "VP of Engineering",
    status: "referred",
    dateSent: "2026-02-01",
    message:
      "Hi Sarah, I noticed Stripe is hiring for a Staff Engineer position. Given our conversation about distributed systems at the SF tech meetup, I'd love to get your perspective on the role and team culture.",
  },
  {
    id: "r2",
    targetCompany: "Google",
    targetRole: "Staff Engineer, Infrastructure",
    referrer: "Marcus Johnson",
    referrerTitle: "Staff Engineer",
    status: "sent",
    dateSent: "2026-02-10",
    message:
      "Hi Marcus, I saw the Staff Infra role on Google's careers page. Having followed your work on cloud-native architectures, I'd appreciate any insights on the infrastructure team.",
  },
  {
    id: "r3",
    targetCompany: "Figma",
    targetRole: "Tech Lead, Platform",
    referrer: "Priya Patel",
    referrerTitle: "Tech Lead",
    status: "responded",
    dateSent: "2026-01-28",
    message:
      "Hi Priya, your talk on Figma's collaborative engine was inspiring. I'm very interested in the Tech Lead Platform role and would love to learn more about the team's roadmap.",
  },
  {
    id: "r4",
    targetCompany: "Datadog",
    targetRole: "Principal Engineer",
    referrer: "Lisa Chang",
    referrerTitle: "Director of Engineering",
    status: "referred",
    dateSent: "2026-02-12",
    message:
      "Hi Lisa, thank you for mentioning the Principal Engineer opening at Datadog. I'd be excited to bring my observability and distributed systems experience to the team.",
  },
];

const activityFeed = [
  {
    id: "act1",
    type: "application",
    title: "Applied to Principal Engineer at Datadog",
    time: "2 hours ago",
    icon: "send",
  },
  {
    id: "act2",
    type: "referral",
    title: "Lisa Chang submitted your referral at Datadog",
    time: "5 hours ago",
    icon: "userCheck",
  },
  {
    id: "act3",
    type: "interview",
    title: "Interview scheduled with Stripe - Feb 20",
    time: "1 day ago",
    icon: "calendar",
  },
  {
    id: "act4",
    type: "offer",
    title: "Received offer from Figma - $280K base",
    time: "2 days ago",
    icon: "trophy",
  },
  {
    id: "act5",
    type: "connection",
    title: "Sarah Chen accepted your connection request",
    time: "3 days ago",
    icon: "userPlus",
  },
  {
    id: "act6",
    type: "match",
    title: "New 96% match: Staff Engineer at Stripe",
    time: "3 days ago",
    icon: "zap",
  },
  {
    id: "act7",
    type: "interview",
    title: "Passed coding round at Google",
    time: "4 days ago",
    icon: "checkCircle",
  },
  {
    id: "act8",
    type: "network",
    title: "AI sent follow-up to Marcus Johnson",
    time: "5 days ago",
    icon: "messageCircle",
  },
];

const networkGrowthData = {
  labels: ["Sep", "Oct", "Nov", "Dec", "Jan", "Feb"],
  values: [45, 68, 92, 128, 156, 189],
};

const applicationStatsData = {
  labels: ["Applied", "Screening", "Interview", "Offer", "Rejected"],
  values: [3, 2, 2, 1, 1],
  colors: [
    "rgba(59, 130, 246, 0.8)",
    "rgba(245, 158, 11, 0.8)",
    "rgba(139, 92, 246, 0.8)",
    "rgba(16, 185, 129, 0.8)",
    "rgba(244, 63, 94, 0.8)",
  ],
};

const weeklyApplications = {
  labels: ["W1 Jan", "W2 Jan", "W3 Jan", "W4 Jan", "W1 Feb", "W2 Feb", "W3 Feb"],
  values: [2, 1, 3, 2, 4, 1, 3],
};

const followUps = [
  {
    id: "f1",
    contactName: "James Wilson",
    company: "Google",
    scheduledDate: "2026-02-18",
    type: "Recruiter Follow-up",
    aiMessage:
      "Hi James, following up on our conversation about the Staff Infrastructure role. I've since completed a Kubernetes certification that aligns with the team's tech stack. Would love to reconnect.",
    status: "scheduled",
  },
  {
    id: "f2",
    contactName: "Sarah Chen",
    company: "Stripe",
    scheduledDate: "2026-02-19",
    type: "Post-referral Thank You",
    aiMessage:
      "Hi Sarah, wanted to express my gratitude for referring me to the Staff Engineer position. I had the initial screen last week and it went well. Looking forward to keeping you posted on the process.",
    status: "scheduled",
  },
  {
    id: "f3",
    contactName: "Emily Rodriguez",
    company: "Vercel",
    scheduledDate: "2026-02-20",
    type: "Informational Interview",
    aiMessage:
      "Hi Emily, I'd love to learn more about the engineering culture at Vercel and how the team approaches frontend architecture at scale. Would you be open to a 20-minute chat?",
    status: "pending",
  },
];

module.exports = {
  userProfile,
  jobListings,
  connections,
  applications,
  referrals,
  activityFeed,
  networkGrowthData,
  applicationStatsData,
  weeklyApplications,
  followUps,
};
